### ISSUE TITLE
Some help?

### ISSUE THREAD

**Issue by niai** [Xakep16/android_device_oukitel_k6#1]
I know your probably not interested in helping me and I am new to this, but when I try to build I am stuck with needing additional files that I can not find on my phone. Do I need to get them from another source? Also is building a rom even possible as the kernel has not been released?

I want to help if at all possible.

These are just a few of them
`caution: filename not matched:  system/bin/qmc6983d
caution: filename not matched:  system/bin/6620_launcher
caution: filename not matched:  system/bin/mtkrildmd2
caution: filename not matched:  system/bin/mtkrild
caution: filename not matched:  system/bin/gsm0710muxdmd2
caution: filename not matched:  system/etc/nfc.cfg
caution: filename not matched:  system/etc/fmr/mt6627_fm_cust.cfg
caution: filename not matched:  system/etc/bluetooth/bt_stack.conf.sqc
caution: filename not matched:  system/etc/bluetooth/bt_stack.conf.debug
caution: filename not matched:  system/etc/bluetooth/auto_pair_devlist.conf
caution: filename not matched:  system/etc/firmware/dsp_1_ltg_n.bin
caution: filename not matched:  system/etc/firmware/modem_1_lwg_n.img
caution: filename not matched:  system/etc/firmware/mt6627/mt6627_fm_v5_coeff.bin
caution: filename not matched:  system/etc/firmware/mt6627/mt6627_fm_v2_coeff.bin
caution: filename not matched:  system/etc/firmware/mt6627/mt6627_fm_v2_patch.bin
caution: filename not matched:  system/etc/firmware/mt6627/mt6627_fm_v4_patch.bin
caution: filename not matched:  system/etc/firmware/mt6627/mt6627_fm_v3_coeff.bin
caution: filename not matched:  system/etc/firmware/mt6627/mt6627_fm_v3_patch.bin
caution: filename not matched:  system/etc/firmware/mt6627/mt6627_fm_v5_patch.bin
caution: filename not matched:  system/etc/firmware/mt6627/mt6627_fm_v4_coeff.bin
caution: filename not matched:  system/etc/firmware/mt6627/mt6627_fm_v1_coeff.bin
caution: filename not matched:  system/etc/firmware/mt6627/mt6627_fm_v1_patch.bin
`

**Comment by Xakep16** [comment]
Kernel used stock.

**Comment by niai** [comment]
I am using LineageOS 14.1 but getting 
`ninja: error: 'vendor/oukitel/k6/proprietary/bin/qmc6983d', needed by '/mnt/sda3/android/lineage/out/target/product/k6/system/bin/qmc6983d', missing and no known rule to make it`

Its one of the files that needs importing from "unzip-files.sh" in the "proprietary-blobs.txt" file `bin/qmc6983d
`
I can't find it any were on my phone or the stock recovery files.

Thanks for the project and helping.

**Comment by Xakep16** [comment]
https://github.com/Xakep16/android_vendor_oukitel_k6?files=1

Need unpack in vendor/oukitel/k6

You path?

**Comment by niai** [comment]
I have most of the files in "vendor/oukitel/k6", but I am missing a few files that I can not find on my phone.

I also have "android_device_oukitel_k6" in device/oukitel/k6 and "android_vendor_oukitel_k6" in vendor/oukitel/k6.

This is a list of all the files i cant find on my device (found in proprietary-blobs.txt), I have tried doing a search of my phone.

> /bin/qmc6983d
> /bin/6620_launcher
> /bin/mtkrildmd2
> /bin/mtkrild
> /bin/gsm0710muxdmd2
> /etc/nfc.cfg
> /etc/fmr/mt6627_fm_cust.cfg
> /etc/bluetooth/bt_stack.conf.sqc
> /etc/bluetooth/bt_stack.conf.debug
> /etc/bluetooth/auto_pair_devlist.conf
> /etc/firmware/dsp_1_ltg_n.bin
> /etc/firmware/modem_1_lwg_n.img
> /etc/firmware/mt6627/mt6627_fm_v5_coeff.bin
> /etc/firmware/mt6627/mt6627_fm_v2_coeff.bin
> /etc/firmware/mt6627/mt6627_fm_v2_patch.bin
> /etc/firmware/mt6627/mt6627_fm_v4_patch.bin
> /etc/firmware/mt6627/mt6627_fm_v3_coeff.bin
> /etc/firmware/mt6627/mt6627_fm_v3_patch.bin
> /etc/firmware/mt6627/mt6627_fm_v5_patch.bin
> /etc/firmware/mt6627/mt6627_fm_v4_coeff.bin
> /etc/firmware/mt6627/mt6627_fm_v1_coeff.bin
> /etc/firmware/mt6627/mt6627_fm_v1_patch.bin
> /etc/firmware/ROMv2_lm_patch_1_1_hdr.bin
> /etc/firmware/S_ANDRO_SFL.ini
> /etc/firmware/ROMv2_lm_patch_1_0_hdr.bin
> /etc/firmware/catcher_filter_1_ltg_n.bin
> /etc/firmware/dsp_1_lwg_n.bin
> /etc/firmware/catcher_filter_1_lwg_n.bin
> /etc/firmware/WMT_SOC.cfg
> /etc/firmware/WIFI_RAM_CODE_6735
> /etc/firmware/modem_1_ltg_n.img
> /etc/nfc_conformance/DTA_Config/Others/platform_config.txt
> /etc/nfc_conformance/DTA_Config/Others/p2p_polling.txt
> /etc/nfc_conformance/DTA_Config/Others/platform_polling_tagOp.txt
> /etc/nfc_conformance/DTA_Config/Others/platform_polling.txt
> /etc/nfc_conformance/DTA_Config/Others/listen_polling.txt
> /etc/nfc_conformance/DTA_Config/Others/p2p_config.txt
> /etc/nfc_conformance/DTA_Config/Others/listen_config.txt
> /etc/nfc_conformance/DTA_Config/Others/platform_config_tagOp.txt
> /etc/nfc_conformance/DTA_Config/Comprion/platform_config.txt
> /etc/nfc_conformance/DTA_Config/Comprion/p2p_polling.txt
> /etc/nfc_conformance/DTA_Config/Comprion/platform_polling_tagOp.txt
> /etc/nfc_conformance/DTA_Config/Comprion/platform_polling.txt
> /etc/nfc_conformance/DTA_Config/Comprion/listen_polling.txt
> /etc/nfc_conformance/DTA_Config/Comprion/p2p_config.txt
> /etc/nfc_conformance/DTA_Config/Comprion/listen_config.txt
> /etc/nfc_conformance/DTA_Config/Comprion/platform_config_tagOp.txt
> /etc/nfc_conformance/DTA_Config/Clear2Pay/platform_config.txt
> /etc/nfc_conformance/DTA_Config/Clear2Pay/p2p_polling.txt
> /etc/nfc_conformance/DTA_Config/Clear2Pay/platform_polling_tagOp.txt
> /etc/nfc_conformance/DTA_Config/Clear2Pay/platform_polling.txt
> /etc/nfc_conformance/DTA_Config/Clear2Pay/listen_polling.txt
> /etc/nfc_conformance/DTA_Config/Clear2Pay/p2p_config.txt
> /etc/nfc_conformance/DTA_Config/Clear2Pay/listen_config.txt
> /etc/nfc_conformance/DTA_Config/Clear2Pay/platform_config_tagOp.txt
> /etc/nfc_conformance/DTA_Config/AT4/platform_config.txt
> /etc/nfc_conformance/DTA_Config/AT4/p2p_polling.txt
> /etc/nfc_conformance/DTA_Config/AT4/platform_polling_tagOp.txt
> /etc/nfc_conformance/DTA_Config/AT4/platform_polling.txt
> /etc/nfc_conformance/DTA_Config/AT4/listen_polling.txt
> /etc/nfc_conformance/DTA_Config/AT4/p2p_config.txt
> /etc/nfc_conformance/DTA_Config/AT4/listen_config.txt
> /etc/nfc_conformance/DTA_Config/AT4/platform_config_tagOp.txt
> /etc/MTKNfclicense.lic
> /etc/nfcse.cfg
> /lib/libmpoencoder.so
> /lib/liba3m.so
> /lib/libsec.so
> /lib/libcam.sdkclient.so
> /lib/mtk-rilmd2.so
> /lib/libcam.camnode.so
> /lib/libfeatureiodrv.so
> /lib/libMtkOmxVdec.so
> /lib/libcam3_hwnode.so
> /lib/libcam.metadata.so
> /lib/libmpodecoder.so
> /lib/libcam.utils.sensorlistener.so
> /lib/libmtknfc.so
> /lib/mtk-ril.so
> /lib/libbessurround_mtk.so
> /lib/libcamera_client_mtk.so
> /lib/libcam_mmp.so
> /lib/libnvramagentclient.so
> /lib/libm4u.so
> /lib/librilmtk.so
> /lib/libcam.exif.so
> /lib/libcamdrv.so
> /lib/libpq_cust.so
> /lib/libmatv_cust.so
> /lib/libcam.utils.so
> /lib/libmpo.so
> /lib/libmal.so
> /lib/libfgauge.so
> /lib/libmmsdkservice.feature.so
> /lib/libcam.metadataprovider.so
> /lib/libcam_utils.so
> /lib/libcam.utils.cpuctrl.so
> /lib/libfeatureio.so
> /lib/libcam.exif.v3.so
> /lib/libcam_hwutils.so
> /lib/libcam3_pipeline.so
> /lib/libGdmaScalerPipe.so
> /lib/libcam3_utils.so
> /lib/libn3d3a.so
> /lib/libdngop.so
> /lib/libmdfx.so
> /lib/librilmtkmd2.so
> /files.txt
> /xbin/mnld
> /xbin/nfcstackp
> /xbin/BGW
> /lib64/libmpoencoder.so
> /lib64/liba3m.so
> /lib64/libmmsdkservice.so
> /lib64/libcam.sdkclient.so
> /lib64/mtk-rilmd2.so
> /lib64/libcam.camnode.so
> /lib64/libfeatureiodrv.so
> /lib64/libcam3_hwnode.so
> /lib64/libcam.metadata.so
> /lib64/libcam.utils.sensorlistener.so
> /lib64/mtk-ril.so
> /lib64/libcamera_client_mtk.so
> /lib64/libcam_mmp.so
> /lib64/libnvramagentclient.so
> /lib64/libm4u.so
> /lib64/librilmtk.so
> /lib64/libcam.exif.so
> /lib64/libcamdrv.so
> /lib64/libpq_cust.so
> /lib64/libmatv_cust.so
> /lib64/libcam.utils.so
> /lib64/libmpo.so
> /lib64/libmal.so
> /lib64/libmmsdkservice.feature.so
> /lib64/libcam.metadataprovider.so
> /lib64/libcam_utils.so
> /lib64/libcam.utils.cpuctrl.so
> /lib64/libfeatureio.so
> /lib64/libcam.exif.v3.so
> /lib64/libcam_hwutils.so
> /lib64/libcam3_pipeline.so
> /lib64/libGdmaScalerPipe.so
> /lib64/libcam3_utils.so
> /lib64/libn3d3a.so
> /lib64/libdngop.so
> /lib64/libmdfx.so
> /lib64/librilmtkmd2.so


Sorry for bothering you so much.

**Comment by Xakep16** [comment]
Strange, I didn’t have any bugs in the build.
strange that he is looking for you here
vendor / oukitel / k6 / proprietary / bin / qmc6983d,
and the file is in
vendor / oukitel / k6 / bin / qmc6983d

**Comment by Xakep16** [comment]
do not worry. I'll upload a more recent version later. but it is not before sunday

**Comment by niai** [comment]
Sorry seems like "unzip-files.sh" was removing the files, as I said I am new to this and I don't know what the problem was that made me start using "unzip-files.sh".

I have replaced both of the k6 directory's and it starts compiling now but still errors out 
`ninja: Entering directory `.'
[  0% 383/48957] host Java: tagsouplib (/mnt/sda3/android/lineage/out/host/common/obj/JAVA_LIBRARIES/tagsouplib_intermediates/classes)
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
[  1% 581/48957] host Java: antlr-runtime (/mnt/sda3/android/lineage/out/host/common/obj/JAVA_LIBRARIES/antlr-runtime_intermediates/classes)
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
[  1% 606/48957] Lex: aidl <= system/tools/aidl/aidl_language_l.ll
FAILED: /bin/bash -c "prebuilts/misc/linux-x86/flex/flex-2.5.39 -o/mnt/sda3/android/lineage/out/host/linux-x86/obj/STATIC_LIBRARIES/libaidl-common_intermediates/aidl_language_l.cpp system/tools/aidl/aidl_language_l.ll"
flex-2.5.39: loadlocale.c:130: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed.
Aborted (core dumped)
[  1% 606/48957] host Java: guavalib (/mnt/sda3/android/lineage/out/host/common/obj/JAVA_LIBRARIES/guavalib_intermediates/classes)
warning: [options] bootstrap class path not set in conjunction with -source 1.7
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
[  1% 606/48957] target Java: core-all (/mnt/sda3/android/lineage/out/target/common/obj/JAVA_LIBRARIES/core-all_intermediates/classes)
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
ninja: build stopped: subcommand failed.
make: *** [build/core/ninja.mk:152: ninja_wrapper] Error 1
make: Leaving directory '/mnt/sda3/android/lineage'`


I don't know what is wrong now and is a bit beyond my knowledge now. I will wait for the update.

Thanks and again sorry for wasting your time.

**Comment by Xakep16** [comment]
source build/envsetup.sh
time brunch k6

Used for start compile?
Ubuntu or Mint ? Version?
Java 1.8?

**Comment by niai** [comment]
Yes I start it with 
```
source build/envsetup.sh
time brunch k6
```

I am guessing you are not a native English speaker? and are translating?
"Used for start compile?" = it starts to compile

Ubuntu 18.10
openjdk version "1.8.0_191"

**Comment by niai** [comment]
It was clear there was a language barrier, didn't know you were in Russia.

I had to communicate with a Russia developer for another project, it seems google translate isn't to good for English to Russian as he told me to stop using it.

Don't worry about it, you have helped me a lot and I am happy you are working on this. So thank you.

I will wait for your update. I may try Ubuntu 16.10 in a virtual machine.

**Comment by Xakep16** [comment]
1 big bug - 
The main problem is not working mobile communication. and how to fix it I have no thoughts.

**Comment by afaulkner420** [comment]
afaulkner420@gmail.com hangouts add me. I'm English native. Plus, have a good understanding of the Russian. I could meet in the middle, also, I have got very far with the developing. Me and @Xakep16 have been talking alot

**Comment by niai** [comment]
Got it to build last night, I needed to use "export LC_ALL=C" to get it to work something to do with the language of my machine.

When I come to flash it, it was saying "for device k6 and you're running K6", easy fix in the update-script.

It seems to run very good, apart from the no sim card.

@afaulkner420 Only just seeing your message now, thanks for the offer I may take you up on it at some point, for now every thing seems fine.

Thanks again and I look forward to an update, I will try and help if I can even if its just testing.

**Comment by afaulkner420** [comment]
No worries! Glad you figured it out ;) always good when you get it going! It's a good feeling! Always here if you need anything though!
